server:
  port: 8080
  contextPath: /Main

#### LOG level ####
logging:
  level:
    root: INFO

spring:
  profiles: local, default
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/websystique
    username: websystique_user
    password: websystique_pwd
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 15
      maximumPoolSize: 20



