server:
  port: 8080
  contextPath: /SpringBootCRUDApp

#### LOG level ####
logging:
  level:
    root: INFO

spring:
  profiles: local, default
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/websystique
    username: websystique_user
    password: websystique_pwd
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: websystique_user
    password: websystique_pwd
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect



